apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ec-ingress
  namespace: ec-qas
  labels:
    application: ec
    stage: qas
  annotations:
    kubernetes.io/ingress.class: nginx
    # doc: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: ec-qas.deltaww.com
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: ec-frontend-svc
              servicePort: 80
          - path: /api(/|$)(.*)
            backend:
              serviceName: ec-frontend-svc
              servicePort: 80
          - path: /api/auth/(.*)
            backend:
              serviceName: ec-auth-svc
              servicePort: 80
          - path: /api/file/(.*)
            backend:
              serviceName: ec-file-svc
              servicePort: 80
          - path: /api/quotation/(.*)
            backend:
              serviceName: ec-quotation-svc
              servicePort: 80
          - path: /api/vendor/(.*)
            backend:
              serviceName: ec-vendor-svc
              servicePort: 80
          - path: /api/consignment/(.*)
            backend:
              serviceName: ec-consignment-svc
              servicePort: 80
